{% set data= load_setup_py_data() %}
package:
  name: ts-mtaircompressor
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: generic
  entry_points:
    - run_mtaircompressor = lsst.ts.MTAirCompressor.aircompressor_csc:run_mtaircompressor

test:
  requires:
    - ts-conda-build
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-utils
    - pymodbus 2.5.3
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build
    - pymodbus 2.5.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-salobj {{ salobj_version }}
    - ts-idl {{ idl_version }}
    - ts-utils
    - pymodbus 2.5.3
